### ISSUE TITLE
create /user page

### ISSUE THREAD

**Issue by FawziyahAlebiosu** [MLH-Fellowship/0.5.2-cms#11]
can someone clarify for me if this page will render the profile of theOWNER of the contact book? or the profile of the connection they want to view individually?

**Comment by amy-lei** [comment]
> can someone clarify for me if this page will render the profile of theOWNER of the contact book? or the profile of the connection they want to view individually?

The latter: profile of the connection they want to view individually. But that reminds me, we will also need a way to view the profile of the OWNER. perhaps /profile?

**Comment by FawziyahAlebiosu** [comment]
Yup will add /profile as an issue tomorrow morning
