### ISSUE TITLE
Master branch

### ISSUE THREAD

**Issue by ebonnecab** [MLH-Fellowship/0.5.2-cms#13]
It looks like the current main branch is the 'flask barebones' app but we need a master branch that we don't touch except when we are integrating our changes. I think the easiest way to handle it is to rename the current branch 'master' and then @FawziyahAlebiosu can create another branch to work from.

**Comment by FawziyahAlebiosu** [comment]
My bad! I should have created a branch to work on, but I forgot. You’re right, that’s the only way to fix it

**Comment by amy-lei** [comment]
I created a master branch, but it might affect your pull request @ebonnecab . I can update it to be the default after it gets merged.

**Comment by amy-lei** [comment]
Just updated the default branch now that the PR is in!
