### ISSUE TITLE
set up database

### ISSUE THREAD

**Issue by amy-lei** [MLH-Fellowship/0.5.2-cms#3]
Set up our database using SQLite with a contacts table. Contact schema is as follows:
  - id (or google id depending on choice of auth): string,
  - name: string
  - date_met: date object,
  - location: string,
  - email: string,
  - links: array<string>
  - notes: array<string> (or should we have a Note object?)

**Comment by FawziyahAlebiosu** [comment]
@amy-lei @ebonnecab we're also going to need a variable/key for notes; the main point of keeping track of these people is to remember what you learned from meeting them.
comments: string
