### ISSUE TITLE
set up user authentication

### ISSUE THREAD

**Issue by ebonnecab** [MLH-Fellowship/0.5.2-cms#5]
set up user objects in DB + authentication

**Comment by FawziyahAlebiosu** [comment]
@ebonnecab will this be with like google sign-in or which system are you considering using to authenticate users? 
I proposed google above because most people have a google account, but if you have something in mind that will be easier to implement, please share!

**Comment by ebonnecab** [comment]
@FawziyahAlebiosu right now I have a user table that stores their name, username, and password hash. Users can register, login, and logout. It also lets users stay logged in until they logout. I use the werkzeug package to create a password hash and check that it is the correct hash. This is how the Flask tutorial recommended I do it, but we can also research other ways.
