### ISSUE TITLE
create index.html/ home page using wireframe.

### ISSUE THREAD

**Issue by FawziyahAlebiosu** [MLH-Fellowship/0.5.2-cms#8]
how do y'all feel about the homepage having the following:

![image](https://user-images.githubusercontent.com/20774412/83571354-990e1080-a4f5-11ea-8798-c89f7042b956.png)
^^ for the portion that says 'you must be logged in..." that part could be overlayed onto the background, and then the background can be blurred. this way it's simulating how some sites need you to pay before using a product. except, in this case, we need them to log-in to start using it.

- other things to note:
   -  the home page can be one continuous scroll, so that when the user clicks on add, or view at the top right, it will JUMP to that section
  - how do you all feel about making the add template be at the top of the homepage, like the image below:

![image](https://user-images.githubusercontent.com/20774412/83571648-28b3bf00-a4f6-11ea-8fde-f884e5e37b78.png)

^^ instead, we would replace title with name, and modify it to have the items we talked about:
- name,
- email/contact, etc.

and then when the user clicks on contact book, it would jump to this:
![image](https://user-images.githubusercontent.com/20774412/83571810-79c3b300-a4f6-11ea-9de8-64bcf47244d4.png)
and on the side we can ask if the user wants to see it in a different view.  this would mean that global view will be the default. 
finally, at the bottom, it can be a little copyright/license section where our names are at the bottom, to ackowledge that we made it.

**Comment by amy-lei** [comment]
> how do y'all feel about the homepage having the following:

I've noticed some websites have a completely separate homepage before the user logs in/registers. This means other site functionalities won't be available on the homepage (such as add connection or contact book tab) and we wouldn't have to worry about using a popup to block the user from advancing. 

Similar to this site: https://talos.stuy.edu/auth/login/ or like Instagram. 

A quick wireframe of what I mean: 
![image](https://user-images.githubusercontent.com/42757189/83574963-864b0a00-a4fc-11ea-8771-1f41a2a2f1da.png)

**Comment by FawziyahAlebiosu** [comment]
Oooooooh that’s a great idea! Looping back to the previous point in the original issue, this means that this is what the page will look like if the user visits “/“ aka the index page. 

That works with everybody?

**Comment by amy-lei** [comment]
> the home page can be one continuous scroll, so that when the user clicks on add, or view at the top right, it will JUMP to that section
> how do you all feel about making the add template be at the top of the homepage, like the image below

From a user experience standpoint, it might be better to have a separate component/a page/a popup dedicated to adding a new contact? My understanding for including the web app on top of the CLI was to mainly consolidate, organize, and display all of the contacts so that it is easy for the user to maintain.

**Comment by FawziyahAlebiosu** [comment]
> > the home page can be one continuous scroll, so that when the user clicks on add, or view at the top right, it will JUMP to that section
> > how do you all feel about making the add template be at the top of the homepage, like the image below
> 
> From a user experience standpoint, it might be better to have a separate component/a page/a popup dedicated to adding a new contact? My understanding for including the web app on top of the CLI was to mainly consolidate, organize, and display all of the contacts so that it is easy for the user to maintain.

Well it actually looks like that IS what it will end up looking like though. Since we are adopting having the home page be the first place the user signs on/logs on, then we will still end up needing a seperate page(a /add route) anyway. 
With that being said though, unless you and @ebonnecab have any objections to making it a page, I'm going to go ahead and create an issue to make /add a route.
