### ISSUE TITLE
discussion on modifying /viewAll route

### ISSUE THREAD

**Issue by FawziyahAlebiosu** [MLH-Fellowship/0.5.2-cms#9]
after giving it some thought, would you all be okay with moving the viewall function to the bottom of the page, after the add connection section <see issue about homepage for more context>.
if we go this way, we would not need viewAll to be on a seperate page, and we can modify that route to be: viewGroups?

**Comment by FawziyahAlebiosu** [comment]
if this is okay, i will change it on the flask file

**Comment by FawziyahAlebiosu** [comment]
now that i see it, I don't even think this route will be necessary because we already have a /user and a /group route

**Comment by amy-lei** [comment]
> now that i see it, I don't even think this route will be necessary because we already have a /user and a /group route

These were my thoughts behind /all, /group, and /user:
- /all will be for viewing all of the user's contacts in either the map format or card format.  Similar to viewing your friends list on facebook.
- /group will be for viewing the groups you've chose to make and the group info/members when you click to expand on it. Similar to having facebook groups and viewing the members of that group
- /user will be for viewing all notes relevant to a specific user. Similar to viewing a person's facebook profile

Do you still think it's unnecessary to have the three routes?

**Comment by FawziyahAlebiosu** [comment]
> > now that i see it, I don't even think this route will be necessary because we already have a /user and a /group route
> 
> 
> 
> These were my thoughts behind /all, /group, and /user:
> 
> - /all will be for viewing all of the user's contacts in either the map format or card format.  Similar to viewing your friends list on facebook.
> 
> - /group will be for viewing the groups you've chose to make and the group info/members when you click to expand on it. Similar to having facebook groups and viewing the members of that group
> 
> - /user will be for viewing all notes relevant to a specific user. Similar to viewing a person's facebook profile
> 
> 
> 
> Do you still think it's unnecessary to have the three routes?

Thank you for clarifying!! That makes sense now, those are all necessary.
